server:
  port: 8083

spring:
  application:
    name: reserva-service
  datasource:
    url: jdbc:mysql://localhost:3306/rentacar
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

services:
  vehiculo-service:
    url: http://localhost:8081
  cliente-service:
    url: http://localhost:8082

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 